# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Jan  7 09:28:51 2025
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import wx.richtext as rt
# end wxGlade


class AboutWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AboutWindow.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.STAY_ON_TOP | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("About")
        self.SetBackgroundColour(wx.Colour(81, 81, 81))

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        self.sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        self.sizer_1.Add(sizer_2, 1, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 12)

        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_3, 0, wx.RIGHT, 0)

        self.logo_app = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap(50, 50))
        self.logo_app.SetMinSize((50, 50))
        sizer_3.Add(self.logo_app, 0, wx.BOTTOM | wx.RIGHT, 12)

        self.logo_publisher = wx.StaticBitmap(self.panel_1, wx.ID_ANY, wx.Bitmap(50, 50))
        self.logo_publisher.SetMinSize((50, 50))
        sizer_3.Add(self.logo_publisher, 0, wx.TOP, 65)

        self.main_text = rt.RichTextCtrl(self.panel_1, wx.ID_ANY)
        self.main_text.SetBackgroundColour(wx.Colour(81, 81, 81))
        self.main_text.SetForegroundColour(wx.Colour(255, 255, 255))
        self.main_text.SetFont(wx.Font(7, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.main_text.SetWindowStyle(wx.TE_READONLY | wx.TE_MULTILINE | wx.BORDER_NONE | wx.TE_NO_VSCROLL)
        sizer_2.Add(self.main_text, 1, wx.EXPAND, 0)

        self.button_1 = wx.Button(self.panel_1, wx.ID_CLOSE, "")
        self.sizer_1.Add(self.button_1, 0, wx.ALIGN_RIGHT | wx.BOTTOM | wx.RIGHT, 10)

        self.panel_1.SetSizer(self.sizer_1)

        self.sizer_1.Fit(self)
        self.Layout()

        self.Bind(wx.EVT_TEXT_URL, self.on_url_click, self.main_text)
        self.Bind(wx.EVT_BUTTON, self.on_close, self.button_1)
        self.Bind(wx.EVT_CLOSE, self.on_close, self)
        # end wxGlade

    def on_url_click(self, event):  # wxGlade: AboutWindow.<event_handler>
        print("Event handler 'on_url_click' not implemented!")
        event.Skip()

    def on_close(self, event):  # wxGlade: AboutWindow.<event_handler>
        print("Event handler 'on_close' not implemented!")
        event.Skip()

# end of class AboutWindow
