# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.1.0 on Fri Apr 11 11:32:40 2025
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
import wx.lib.agw.thumbnailctrl as TC
from wx.lib.agw.scrolledthumbnail import PILImageHandler
# end wxGlade


class EmojiSelectorWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: EmojiSelectorWindow.__init__
        kwds["style"] = kwds.get("style", 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.FULL_REPAINT_ON_RESIZE | wx.RESIZE_BORDER | wx.STAY_ON_TOP
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 300))
        self.SetTitle("EmojiSelector")

        self.panel_1 = wx.Panel(self, wx.ID_ANY, style=wx.BORDER_NONE | wx.FULL_REPAINT_ON_RESIZE)

        self.sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.emoji_selector = TC.ThumbnailCtrl(self.panel_1, wx.ID_ANY, thumboutline=TC.THUMB_OUTLINE_NONE, imagehandler=PILImageHandler)
        self.scrolledThumbNail = self.emoji_selector.GetChildren()[1]
        self.scrolledThumbNail.SetThumbSize(27, 27, 3)
        self.sizer_1.Add(self.emoji_selector, 1, wx.EXPAND, 0)

        self.panel_1.SetSizer(self.sizer_1)

        self.Layout()

        self.emoji_selector.Bind(wx.EVT_LIST_ITEM_SELECTED, self.on_emoji_click)
        self.Bind(wx.EVT_ACTIVATE, self.on_window_activate)
        self.Bind(wx.EVT_CLOSE, self.on_close)
        self.Bind(wx.EVT_MENU_CLOSE, self.on_close)
        self.Bind(wx.EVT_SHOW, self.on_show)
        self.Bind(wx.EVT_SIZE, self.on_resize)
        # end wxGlade

    def on_emoji_click(self, event):  # wxGlade: EmojiSelectorWindow.<event_handler>
        print("Event handler 'on_emoji_click' not implemented!")
        event.Skip()

    def on_window_activate(self, event):  # wxGlade: EmojiSelectorWindow.<event_handler>
        print("Event handler 'on_window_activate' not implemented!")
        event.Skip()

    def on_close(self, event):  # wxGlade: EmojiSelectorWindow.<event_handler>
        print("Event handler 'on_close' not implemented!")
        event.Skip()

    def on_show(self, event):  # wxGlade: EmojiSelectorWindow.<event_handler>
        print("Event handler 'on_show' not implemented!")
        event.Skip()

    def on_resize(self, event):  # wxGlade: EmojiSelectorWindow.<event_handler>
        print("Event handler 'on_resize' not implemented!")
        event.Skip()

# end of class EmojiSelectorWindow
