#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Dec 24 16:37:01 2024
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
from MainWindow import MainWindow


class MainApp(wx.App):
    def OnInit(self):
        self.MainWindow = MainWindow(None, wx.ID_ANY, "")
        self.SetTopWindow(self.MainWindow)
        self.MainWindow.Show()
        return True

# end of class MainApp

if __name__ == "__main__":
    MainApp = MainApp(0)
    MainApp.MainLoop()
