# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Wed Mar 15 11:58:43 2023
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ChatWindow(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ChatWindow.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((300, 300))
        self.SetTitle("Chat Window")

        # Menu Bar
        self.MainFrame_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Settings", "")
        self.Bind(wx.EVT_MENU, self.OpenSettings, item)
        item = wxglade_tmp_menu.Append(wx.ID_ANY, "Clear Chat", "")
        self.Bind(wx.EVT_MENU, self.ClearChat, item)
        self.MainFrame_menubar.Append(wxglade_tmp_menu, "Settings")
        self.SetMenuBar(self.MainFrame_menubar)
        # Menu Bar end

        self.MainFrame_statusbar = self.CreateStatusBar(1)
        self.MainFrame_statusbar.SetStatusWidths([-1])

        self.splitter_window = wx.SplitterWindow(self, wx.ID_ANY, style=wx.SP_3D | wx.SP_LIVE_UPDATE)
        self.splitter_window.SetMinimumPaneSize(50)
        self.splitter_window.SetSashGravity(1.0)

        self.panel_chat_log = wx.ScrolledWindow(self.splitter_window, wx.ID_ANY, style=wx.TAB_TRAVERSAL)
        self.panel_chat_log.SetBackgroundColour(wx.SystemSettings.GetColour(wx.SYS_COLOUR_BACKGROUND))
        self.panel_chat_log.SetScrollRate(10, 10)

        self.sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.panel_send = wx.Panel(self.splitter_window, wx.ID_ANY)

        sizer_2 = wx.BoxSizer(wx.VERTICAL)

        static_line_1 = wx.StaticLine(self.panel_send, wx.ID_ANY)
        sizer_2.Add(static_line_1, 0, wx.EXPAND, 0)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(sizer_3, 1, wx.EXPAND, 0)

        self.Send = wx.Button(self.panel_send, wx.ID_ANY, "Send")
        self.Send.SetMinSize((75, 30))
        sizer_3.Add(self.Send, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        self.text_ctrl_message = wx.TextCtrl(self.panel_send, wx.ID_ANY, "",
                                             style=wx.TE_AUTO_URL | wx.TE_MULTILINE | wx.TE_PROCESS_ENTER)
        self.text_ctrl_message.Bind(wx.EVT_KEY_DOWN, self.OnKey, self.text_ctrl_message)
        sizer_3.Add(self.text_ctrl_message, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_send.SetSizer(sizer_2)

        self.panel_chat_log.SetSizer(self.sizer_1)

        self.splitter_window.SplitHorizontally(self.panel_chat_log, self.panel_send, 218)

        self.Layout()
        self.SetMinSize(wx.Size(300, 300))
        self.SetName("ChatWindow")

        self.Bind(wx.EVT_BUTTON, self.SendMessage, self.Send)
        self.Bind(wx.EVT_CLOSE, self.OnClose, self)
        self.Bind(wx.EVT_SHOW, self.OnOpen, self)
        # end wxGlade

    def OpenSettings(self, event):  # wxGlade: ChatWindow.<event_handler>
        print("Event handler 'OpenSettings' not implemented!")
        event.Skip()

    def ClearChat(self, event):  # wxGlade: ChatWindow.<event_handler>
        print("Event handler 'ClearChat' not implemented!")
        event.Skip()

    def SendMessage(self, event):  # wxGlade: ChatWindow.<event_handler>
        print("Event handler 'SendMessage' not implemented!")
        event.Skip()

    def OnClose(self, event):  # wxGlade: ChatWindow.<event_handler>
        print("Event handler 'OnClose' not implemented!")
        event.Skip()

    def OnOpen(self, event):  # wxGlade: ChatWindow.<event_handler>
        print("Event handler 'OnOpen' not implemented!")
        event.Skip()

# end of class ChatWindow
