# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Fri Mar 10 09:40:09 2023
#

import wx


# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class SettingsWindow_New(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SettingsWindow_New.__init__
        kwds["style"] = kwds.get("style",
                                 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.FRAME_FLOAT_ON_PARENT | wx.FRAME_NO_TASKBAR | wx.STAY_ON_TOP | wx.SYSTEM_MENU | wx.TAB_TRAVERSAL
        wx.Frame.__init__(self, *args, **kwds)
        self.SetTitle("Settings")
        self.SetFocus()

        self.panel_Main = wx.Panel(self, wx.ID_ANY)

        sizer_Main = wx.BoxSizer(wx.VERTICAL)

        sizer_LocalUser = wx.StaticBoxSizer(wx.StaticBox(self.panel_Main, wx.ID_ANY, "Local User"), wx.HORIZONTAL)
        sizer_Main.Add(sizer_LocalUser, 0, wx.EXPAND | wx.LEFT | wx.RIGHT | wx.TOP, 5)

        label_Local_Name = wx.StaticText(self.panel_Main, wx.ID_ANY, "Name:")
        label_Local_Name.SetMinSize((40, 20))
        sizer_LocalUser.Add(label_Local_Name, 0, wx.ALL, 2)

        self.text_ctrl_Local_Name = wx.TextCtrl(self.panel_Main, wx.ID_ANY, "")
        self.text_ctrl_Local_Name.SetMinSize((100, 20))
        sizer_LocalUser.Add(self.text_ctrl_Local_Name, 1, wx.ALL | wx.EXPAND, 2)

        label_RemoteUsers = wx.StaticText(self.panel_Main, wx.ID_ANY, "Remote Users:")
        sizer_Main.Add(label_RemoteUsers, 0, wx.LEFT | wx.TOP, 5)

        self.sizer_RemoteUsers = wx.BoxSizer(wx.VERTICAL)
        sizer_Main.Add(self.sizer_RemoteUsers, 0, 0, 0)

        sizer_User1_Main = wx.StaticBoxSizer(wx.StaticBox(self.panel_Main, wx.ID_ANY, "User 1"), wx.HORIZONTAL)
        self.sizer_RemoteUsers.Add(sizer_User1_Main, 0, wx.LEFT | wx.RIGHT | wx.TOP, 5)

        self.button_User1_Subtract = wx.Button(self.panel_Main, wx.ID_ANY, "-")
        self.button_User1_Subtract.SetMinSize((30, 30))
        self.button_User1_Subtract.SetForegroundColour(wx.Colour(216, 0, 0))
        self.button_User1_Subtract.SetFont(
            wx.Font(18, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_User1_Main.Add(self.button_User1_Subtract, 0, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 5)

        sizer_User1_Sub = wx.BoxSizer(wx.VERTICAL)
        sizer_User1_Main.Add(sizer_User1_Sub, 1, wx.EXPAND, 0)

        sizer_User1_DeviceName = wx.BoxSizer(wx.HORIZONTAL)
        sizer_User1_Sub.Add(sizer_User1_DeviceName, 1, wx.EXPAND, 0)

        label_User1_DeviceName = wx.StaticText(self.panel_Main, wx.ID_ANY, "Device Name:")
        label_User1_DeviceName.SetMinSize((80, 20))
        sizer_User1_DeviceName.Add(label_User1_DeviceName, 0, wx.ALL, 2)

        self.text_ctrl_User1_DeviceName = wx.TextCtrl(self.panel_Main, wx.ID_ANY, "")
        self.text_ctrl_User1_DeviceName.SetMinSize((100, 20))
        sizer_User1_DeviceName.Add(self.text_ctrl_User1_DeviceName, 0, wx.ALL, 2)

        sizer_User1_Alias = wx.BoxSizer(wx.HORIZONTAL)
        sizer_User1_Sub.Add(sizer_User1_Alias, 1, wx.EXPAND, 0)

        label_User1_Alias = wx.StaticText(self.panel_Main, wx.ID_ANY, "Alias:")
        label_User1_Alias.SetMinSize((80, 20))
        sizer_User1_Alias.Add(label_User1_Alias, 0, wx.ALL, 2)

        self.text_ctrl_User1_Alias = wx.TextCtrl(self.panel_Main, wx.ID_ANY, "")
        self.text_ctrl_User1_Alias.SetMinSize((100, 20))
        sizer_User1_Alias.Add(self.text_ctrl_User1_Alias, 0, wx.ALL, 2)

        self.checkbox_User1_AliasOverride = wx.CheckBox(self.panel_Main, wx.ID_ANY, "Override Alias?")
        sizer_User1_Sub.Add(self.checkbox_User1_AliasOverride, 0, wx.ALL, 3)

        self.button_AddUser = wx.Button(self.panel_Main, wx.ID_ANY, "+")
        self.button_AddUser.SetMinSize((30, 30))
        self.button_AddUser.SetForegroundColour(wx.Colour(0, 195, 0))
        self.button_AddUser.SetFont(
            wx.Font(14, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_Main.Add(self.button_AddUser, 1, wx.BOTTOM | wx.LEFT | wx.TOP, 5)

        sizer_ApplyCancel = wx.BoxSizer(wx.HORIZONTAL)
        sizer_Main.Add(sizer_ApplyCancel, 0, wx.ALL | wx.EXPAND, 0)

        self.button_Apply = wx.Button(self.panel_Main, wx.ID_ANY, "Apply")
        self.button_Apply.SetMinSize((75, 30))
        sizer_ApplyCancel.Add(self.button_Apply, 1, wx.ALL | wx.EXPAND, 5)

        self.button_Cancel = wx.Button(self.panel_Main, wx.ID_ANY, "Cancel")
        self.button_Cancel.SetMinSize((75, 30))
        sizer_ApplyCancel.Add(self.button_Cancel, 1, wx.ALL | wx.EXPAND, 5)

        self.panel_Main.SetSizer(sizer_Main)

        sizer_Main.Fit(self)
        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.Subtract_OnClick, self.button_User1_Subtract)
        self.Bind(wx.EVT_BUTTON, self.Add_OnClick, self.button_AddUser)
        self.Bind(wx.EVT_BUTTON, self.Apply_OnClick, self.button_Apply)
        self.Bind(wx.EVT_BUTTON, self.Cancel_OnClick, self.button_Cancel)
        self.Bind(wx.EVT_CLOSE, self.OnClose, self)
        self.Bind(wx.EVT_MENU_OPEN, self.OnOpen, self)
        self.Bind(wx.EVT_SHOW, self.OnOpen, self)
        # end wxGlade

    def Subtract_OnClick(self, event):  # wxGlade: SettingsWindow_New.<event_handler>
        print("Event handler 'Subtract_OnClick' not implemented!")
        event.Skip()

    def Add_OnClick(self, event):  # wxGlade: SettingsWindow_New.<event_handler>
        print("Event handler 'Add_OnClick' not implemented!")
        event.Skip()

    def Apply_OnClick(self, event):  # wxGlade: SettingsWindow_New.<event_handler>
        print("Event handler 'Apply_OnClick' not implemented!")
        event.Skip()

    def Cancel_OnClick(self, event):  # wxGlade: SettingsWindow_New.<event_handler>
        print("Event handler 'Cancel_OnClick' not implemented!")
        event.Skip()

    def OnClose(self, event):  # wxGlade: SettingsWindow_New.<event_handler>
        print("Event handler 'OnClose' not implemented!")
        event.Skip()

    def OnOpen(self, event):  # wxGlade: SettingsWindow_New.<event_handler>
        print("Event handler 'OnOpen' not implemented!")
        event.Skip()

# end of class SettingsWindow_New
